### PR TITLE
Add `CODE_OF_CONDUCT.md`

### PR DESCRIPTION
**Pull request by flarnie**
It's great that this project has a Code of Conduct! Github expects there to be a separate `CODE_OF_CONDUCT.md` file for their community standards - let's add this file in order to make it clear that this project has support for a healthy open source community.

why make this change?:
Exposing the COC via a separate markdown file is a standard being
promoted by Github via the Community Profile in order to meet their Open
Source Guide's recommended community standards.

As you can see, adding this file will improve the [fb-util-for-appx community profile
checklist](https://github.com/facebook/fb-util-for-appx/community) and increase the visibility of the COC for this project.

test plan:
Viewing it on my branch -
screen shot 2017-12-18 at 7 40 13 am

issue:
internal task t23481323

### CODE REVIEW

**Comment by strager** [comment]
@flarnie, it looks like the linked code of conduct isn't going to be maintained:

> Update: We will not be continuing work on the open code of conduct. See [our followup post](http://todogroup.org/blog/followup-open-code-of-conduct/) for more information.
>
> We recommend you adopt a code of conduct that fits the needs of your community.

The linked code of conduct has a "[CONTACT]" placeholder in the "Reporting Issues" section. Did you intend to fill that placeholder somehow?

**Comment by strager** [comment]
Despite these issues, the change looks fine. I'll land it.

**Comment by flarnie** [comment]
Thanks @strager - I was going with the COC already listed in this project, feel free to switch to the [Facebook COC](https://code.facebook.com/pages/876921332402685/open-source-code-of-conduct).

And thanks!!

**Comment by strager** [comment]
@flarnie, oh, I didn't notice. That makes sense.

**Pull request merged**
